# Generated by Django 4.1.3 on 2023-01-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timeadata', models.DateTimeField()),
            ],
        ),
    ]
